export default {
    data(){
        return{
            lang:{
                en:{
                    website:{
                        label:"website",
                        placeholder:"https://example.com"
                    },
                    facebook:{
                        label:"facebook",
                        placeholder:"https://facebook.com"
                    },
                    youtube:{
                        label:"youtube",
                        placeholder:"https://youtube.com"
                    },
                    instagram:{
                        label:"instagram",
                        placeholder:"https://instagram.com"
                    },
                    whatsapp:{
                        label:"whatsapp",
                        placeholder:"0123456789"
                    },
                },
                ar:{
                    website:{
                        label:"الموقع الالكتروني",
                        placeholder:"https://example.com"
                    },
                    facebook:{
                        label:"فيس بوك",
                        placeholder:"https://facebook.com"
                    },
                    youtube:{
                        label:"يوتيوب",
                        placeholder:"https://youtube.com"
                    },
                    instagram:{
                        label:"انستجرام",
                        placeholder:"https://instagram.com"
                    },
                    whatsapp:{
                        label:"واتساب",
                        placeholder:"0123456789"
                    },
                }
            }
        }
    }
}