export default {
    data(){
        return{
            dominantEyeOptions:[
                {english:"O.S",arabic:"O.S"},
                {english:"O.D",arabic:"O.D"},
                {english:"O.U",arabic:"O.U"},
            ],
            methodOptions:[
                {english:"Alignment",arabic:"Alignment"},
                {english:"Lens Fogging",arabic:"Lens Fogging"},
                {english:"other",arabic:"other"},
            ],
            brucknerOdOptions:[
                {english:"Deep Red Reflex",arabic:"Deep Red Reflex"},
                {english:"Light Red Reflex",arabic:"Light Red Reflex"},
                {english:"other",arabic:"other"},
            ],
            brucknerOsOptions:[
                {english:"Deep Red Reflex",arabic:"Deep Red Reflex"},
                {english:"Light Red Reflex",arabic:"Light Red Reflex"},
                {english:"other",arabic:"other"},
            ],
            hirschbergOdOptions:[
                {english:"Ortho",arabic:"Ortho"},
                {english:"Esotropia",arabic:"Esotropia"},
                {english:"Exotropia",arabic:"Exotropia"},
                {english:"Hypertropia",arabic:"Hypertropia"},
                {english:"Hypotropia",arabic:"Hypotropia"},
                {english:"other",arabic:"other"},
            ],
            hirschbergOsOptions:[
                {english:"Ortho",arabic:"Ortho"},
                {english:"Esotropia",arabic:"Esotropia"},
                {english:"Exotropia",arabic:"Exotropia"},
                {english:"Hypertropia",arabic:"Hypertropia"},
                {english:"Hypotropia",arabic:"Hypotropia"},
                {english:"other",arabic:"other"},
            ],
            autoPerimetryOdOptions:[
                {english:"Full",arabic: "Full"},
                {english:"Nasal step",arabic: "Nasal step"},
                {english:"temporal wedge",arabic: "temporal wedge"},
                {english:"superior arcuate defect",arabic: "superior arcuate defect"},
                {english:"inferior arcuate defect",arabic: "inferior arcuate defect"},
                {english:"tunnel vision",arabic: "tunnel vision"},
                {english:"enlarged blind spot",arabic: "enlarged blind spot"},
                {english:"homonymous hemianopia",arabic: "homonymous hemianopia"},
                {english:"bitemporal hemianopia",arabic: "bitemporal hemianopia"},
                {english:"central scotoma",arabic: "central scotoma"},
                {english:"centrocaecal scotoma",arabic: "centrocaecal scotoma"},
                {english:"other",arabic:"other"},
            ],
            autoPerimetryOsOptions:[
                {english:"Full",arabic: "Full"},
                {english:"Nasal step",arabic: "Nasal step"},
                {english:"temporal wedge",arabic: "temporal wedge"},
                {english:"superior arcuate defect",arabic: "superior arcuate defect"},
                {english:"inferior arcuate defect",arabic: "inferior arcuate defect"},
                {english:"tunnel vision",arabic: "tunnel vision"},
                {english:"enlarged blind spot",arabic: "enlarged blind spot"},
                {english:"homonymous hemianopia",arabic: "homonymous hemianopia"},
                {english:"bitemporal hemianopia",arabic: "bitemporal hemianopia"},
                {english:"central scotoma",arabic: "central scotoma"},
                {english:"centrocaecal scotoma",arabic: "centrocaecal scotoma"},
                {english:"other",arabic:"other"},
            ],
            confrontationOdOptions:[
                {english:"Full",arabic:"Full"},
                {english:"Diminished",arabic:"Diminished"},
                {english:"other",arabic:"other"},
            ],
            confrontationOsOptions:[
                {english:"Full",arabic:"Full"},
                {english:"Diminished",arabic:"Diminished"},
                {english:"other",arabic:"other"},
            ],
            instrumentOptions:[
                {english:"Humphrey",arabic:"Humphrey"},
                {english:"MRF",arabic:"MRF"},
                {english:"Medmont",arabic:"Medmont"},
                {english:"Oculus",arabic:"Oculus"},
                {english:"Matrix",arabic:"Matrix"},
                {english:"other",arabic:"other"},
            ],
            scaleOptions:[
                {english:"1/1000",arabic: "1/1000"},
                {english:"3/1000",arabic: "3/1000"},
                {english:"5/1000",arabic: "5/1000"},
                {english:"10/1000",arabic: "10/1000"},
                {english:"other",arabic: "other"},
            ],
            colorOdOptions:[
                {english:"Normal",arabic:"Normal"}, 
                {english:"Deuteranomaly",arabic:"Deuteranomaly"}, 
                {english:"Deuteranopia",arabic:"Deuteranopia"}, 
                {english:"Protanomaly",arabic:"Protanomaly"}, 
                {english:"Protanopia",arabic:"Protanopia"}, 
                {english:"Tritanopia",arabic:"Tritanopia"}, 
                {english:"monochromacy",arabic:"monochromacy"}, 
                {english:"other",arabic:"other"}, 
            ],
            colorOsOptions:[
                {english:"Normal",arabic:"Normal"}, 
                {english:"Deuteranomaly",arabic:"Deuteranomaly"}, 
                {english:"Deuteranopia",arabic:"Deuteranopia"}, 
                {english:"Protanomaly",arabic:"Protanomaly"}, 
                {english:"Protanopia",arabic:"Protanopia"}, 
                {english:"Tritanopia",arabic:"Tritanopia"}, 
                {english:"monochromacy",arabic:"monochromacy"}, 
                {english:"other",arabic:"other"}, 
            ],
            colorOuOptions:[
                {english:"Normal",arabic:"Normal"}, 
                {english:"Deuteranomaly",arabic:"Deuteranomaly"}, 
                {english:"Deuteranopia",arabic:"Deuteranopia"}, 
                {english:"Protanomaly",arabic:"Protanomaly"}, 
                {english:"Protanopia",arabic:"Protanopia"}, 
                {english:"Tritanopia",arabic:"Tritanopia"}, 
                {english:"monochromacy",arabic:"monochromacy"}, 
                {english:"other",arabic:"other"}, 
            ],
            colorTestOptions:[
                {english:"D-15",arabic:"D-15"}, 
                {english:"Ishihara",arabic:"Ishihara"}, 
                {english:"Ishihara (Path)",arabic:"Ishihara (Path)"}, 
                {english:"other",arabic:"other"}, 
            ],
            stereoFlyOptions:[
                {english:"Normal Stereopsis",arabic:"Normal Stereopsis"},
                {english:"top of upper wings",arabic:"top of upper wings"},
                {english:"bottom of lower wings",arabic:"bottom of lower wings"},
                {english:"tip of abdomen",arabic:"tip of abdomen"},
                {english:"none seen",arabic:"none seen"},
                {english:"other",arabic:"other"},
            ],
        }
    }
}