export default{
  data(){
    return{
      countries:[
        {
          englishName: "Afghanistan",
          arabicName: "افغانستان",
          region: "Asia",
          flag: "https://upload.wikimedia.org/wikipedia/commons/5/5c/Flag_of_the_Taliban.svg",
        },
        {
          englishName: "Åland Islands",
          arabicName: "جزایر الند",
          region: "Europe",
          flag: "https://flagcdn.com/ax.svg",
        },
        {
          englishName: "Albania",
          arabicName: "آلبانی",
          region: "Europe",
          flag: "https://flagcdn.com/al.svg",
        },
        {
          englishName: "Algeria",
          arabicName: "الجزایر",
          region: "Africa",
          flag: "https://flagcdn.com/dz.svg",
        },
        {
          englishName: "American Samoa",
          arabicName: "ساموآی آمریکا",
          region: "Oceania",
          flag: "https://flagcdn.com/as.svg",
        },
        {
          englishName: "Andorra",
          arabicName: "آندورا",
          region: "Europe",
          flag: "https://flagcdn.com/ad.svg",
        },
        {
          englishName: "Angola",
          arabicName: "آنگولا",
          region: "Africa",
          flag: "https://flagcdn.com/ao.svg",
        },
        {
          englishName: "Anguilla",
          arabicName: "آنگویلا",
          region: "Americas",
          flag: "https://flagcdn.com/ai.svg",
        },
        {
          englishName: "Antarctica",
          arabicName: "جنوبگان",
          region: "Polar",
          flag: "https://flagcdn.com/aq.svg",
        },
        {
          englishName: "Antigua and Barbuda",
          arabicName: "آنتیگوا و باربودا",
          region: "Americas",
          flag: "https://flagcdn.com/ag.svg",
        },
        {
          englishName: "Argentina",
          arabicName: "آرژانتین",
          region: "Americas",
          flag: "https://flagcdn.com/ar.svg",
        },
        {
          englishName: "Armenia",
          arabicName: "ارمنستان",
          region: "Asia",
          flag: "https://flagcdn.com/am.svg",
        },
        {
          englishName: "Aruba",
          arabicName: "آروبا",
          region: "Americas",
          flag: "https://flagcdn.com/aw.svg",
        },
        {
          englishName: "Australia",
          arabicName: "استرالیا",
          region: "Oceania",
          flag: "https://flagcdn.com/au.svg",
        },
        {
          englishName: "Austria",
          arabicName: "اتریش",
          region: "Europe",
          flag: "https://flagcdn.com/at.svg",
        },
        {
          englishName: "Azerbaijan",
          arabicName: "آذربایجان",
          region: "Asia",
          flag: "https://flagcdn.com/az.svg",
        },
        {
          englishName: "Bahamas",
          arabicName: "باهاما",
          region: "Americas",
          flag: "https://flagcdn.com/bs.svg",
        },
        {
          englishName: "Bahrain",
          arabicName: "بحرین",
          region: "Asia",
          flag: "https://flagcdn.com/bh.svg",
        },
        {
          englishName: "Bangladesh",
          arabicName: "بنگلادش",
          region: "Asia",
          flag: "https://flagcdn.com/bd.svg",
        },
        {
          englishName: "Barbados",
          arabicName: "باربادوس",
          region: "Americas",
          flag: "https://flagcdn.com/bb.svg",
        },
        {
          englishName: "Belarus",
          arabicName: "بلاروس",
          region: "Europe",
          flag: "https://flagcdn.com/by.svg",
        },
        {
          englishName: "Belgium",
          arabicName: "بلژیک",
          region: "Europe",
          flag: "https://flagcdn.com/be.svg",
        },
        {
          englishName: "Belize",
          arabicName: "بلیز",
          region: "Americas",
          flag: "https://flagcdn.com/bz.svg",
        },
        {
          englishName: "Benin",
          arabicName: "بنین",
          region: "Africa",
          flag: "https://flagcdn.com/bj.svg",
        },
        {
          englishName: "Bermuda",
          arabicName: "برمودا",
          region: "Americas",
          flag: "https://flagcdn.com/bm.svg",
        },
        {
          englishName: "Bhutan",
          arabicName: "بوتان",
          region: "Asia",
          flag: "https://flagcdn.com/bt.svg",
        },
        {
          englishName: "Bolivia (Plurinational State of)",
          arabicName: "بولیوی",
          region: "Americas",
          flag: "https://flagcdn.com/bo.svg",
        },
        {
          englishName: "Bonaire, Sint Eustatius and Saba",
          arabicName: "بونیر",
          region: "Americas",
          flag: "https://flagcdn.com/bq.svg",
        },
        {
          englishName: "Bosnia and Herzegovina",
          arabicName: "بوسنی و هرزگوین",
          region: "Europe",
          flag: "https://flagcdn.com/ba.svg",
        },
        {
          englishName: "Botswana",
          arabicName: "بوتسوانا",
          region: "Africa",
          flag: "https://flagcdn.com/bw.svg",
        },
        {
          englishName: "Bouvet Island",
          arabicName: "جزیره بووه",
          region: "Antarctic Ocean",
          flag: "https://flagcdn.com/bv.svg",
        },
        {
          englishName: "Brazil",
          arabicName: "برزیل",
          region: "Americas",
          flag: "https://flagcdn.com/br.svg",
        },
        {
          englishName: "British Indian Ocean Territory",
          arabicName: "قلمرو بریتانیا در اقیانوس هند",
          region: "Africa",
          flag: "https://flagcdn.com/io.svg",
        },
        {
          englishName: "United States Minor Outlying Islands",
          arabicName: "جزایر کوچک حاشیه‌ای ایالات متحده آمریکا",
          region: "Americas",
          flag: "https://flagcdn.com/um.svg",
        },
        {
          englishName: "Virgin Islands (British)",
          arabicName: "جزایر ویرجین بریتانیا",
          region: "Americas",
          flag: "https://flagcdn.com/vg.svg",
        },
        {
          englishName: "Virgin Islands (U.S.)",
          arabicName: "جزایر ویرجین آمریکا",
          region: "Americas",
          flag: "https://flagcdn.com/vi.svg",
        },
        {
          englishName: "Brunei Darussalam",
          arabicName: "برونئی",
          region: "Asia",
          flag: "https://flagcdn.com/bn.svg",
        },
        {
          englishName: "Bulgaria",
          arabicName: "بلغارستان",
          region: "Europe",
          flag: "https://flagcdn.com/bg.svg",
        },
        {
          englishName: "Burkina Faso",
          arabicName: "بورکینافاسو",
          region: "Africa",
          flag: "https://flagcdn.com/bf.svg",
        },
        {
          englishName: "Burundi",
          arabicName: "بوروندی",
          region: "Africa",
          flag: "https://flagcdn.com/bi.svg",
        },
        {
          englishName: "Cambodia",
          arabicName: "کامبوج",
          region: "Asia",
          flag: "https://flagcdn.com/kh.svg",
        },
        {
          englishName: "Cameroon",
          arabicName: "کامرون",
          region: "Africa",
          flag: "https://flagcdn.com/cm.svg",
        },
        {
          englishName: "Canada",
          arabicName: "کانادا",
          region: "Americas",
          flag: "https://flagcdn.com/ca.svg",
        },
        {
          englishName: "Cabo Verde",
          arabicName: "کیپ ورد",
          region: "Africa",
          flag: "https://flagcdn.com/cv.svg",
        },
        {
          englishName: "Cayman Islands",
          arabicName: "جزایر کیمن",
          region: "Americas",
          flag: "https://flagcdn.com/ky.svg",
        },
        {
          englishName: "Central African Republic",
          arabicName: "جمهوری آفریقای مرکزی",
          region: "Africa",
          flag: "https://flagcdn.com/cf.svg",
        },
        {
          englishName: "Chad",
          arabicName: "چاد",
          region: "Africa",
          flag: "https://flagcdn.com/td.svg",
        },
        {
          englishName: "Chile",
          arabicName: "شیلی",
          region: "Americas",
          flag: "https://flagcdn.com/cl.svg",
        },
        {
          englishName: "China",
          arabicName: "چین",
          region: "Asia",
          flag: "https://flagcdn.com/cn.svg",
        },
        {
          englishName: "Christmas Island",
          arabicName: "جزیره کریسمس",
          region: "Oceania",
          flag: "https://flagcdn.com/cx.svg",
        },
        {
          englishName: "Cocos (Keeling) Islands",
          arabicName: "جزایر کوکوس",
          region: "Oceania",
          flag: "https://flagcdn.com/cc.svg",
        },
        {
          englishName: "Colombia",
          arabicName: "کلمبیا",
          region: "Americas",
          flag: "https://flagcdn.com/co.svg",
        },
        {
          englishName: "Comoros",
          arabicName: "کومور",
          region: "Africa",
          flag: "https://flagcdn.com/km.svg",
        },
        {
          englishName: "Congo",
          arabicName: "کنگو",
          region: "Africa",
          flag: "https://flagcdn.com/cg.svg",
        },
        {
          englishName: "Congo (Democratic Republic of the)",
          arabicName: "جمهوری کنگو",
          region: "Africa",
          flag: "https://flagcdn.com/cd.svg",
        },
        {
          englishName: "Cook Islands",
          arabicName: "جزایر کوک",
          region: "Oceania",
          flag: "https://flagcdn.com/ck.svg",
        },
        {
          englishName: "Costa Rica",
          arabicName: "کاستاریکا",
          region: "Americas",
          flag: "https://flagcdn.com/cr.svg",
        },
        {
          englishName: "Croatia",
          arabicName: "کرواسی",
          region: "Europe",
          flag: "https://flagcdn.com/hr.svg",
        },
        {
          englishName: "Cuba",
          arabicName: "کوبا",
          region: "Americas",
          flag: "https://flagcdn.com/cu.svg",
        },
        {
          englishName: "Curaçao",
          arabicName: "کوراسائو",
          region: "Americas",
          flag: "https://flagcdn.com/cw.svg",
        },
        {
          englishName: "Cyprus",
          arabicName: "قبرس",
          region: "Europe",
          flag: "https://flagcdn.com/cy.svg",
        },
        {
          englishName: "Czech Republic",
          arabicName: "جمهوری چک",
          region: "Europe",
          flag: "https://flagcdn.com/cz.svg",
        },
        {
          englishName: "Denmark",
          arabicName: "دانمارک",
          region: "Europe",
          flag: "https://flagcdn.com/dk.svg",
        },
        {
          englishName: "Djibouti",
          arabicName: "جیبوتی",
          region: "Africa",
          flag: "https://flagcdn.com/dj.svg",
        },
        {
          englishName: "Dominica",
          arabicName: "دومینیکا",
          region: "Americas",
          flag: "https://flagcdn.com/dm.svg",
        },
        {
          englishName: "Dominican Republic",
          arabicName: "جمهوری دومینیکن",
          region: "Americas",
          flag: "https://flagcdn.com/do.svg",
        },
        {
          englishName: "Ecuador",
          arabicName: "اکوادور",
          region: "Americas",
          flag: "https://flagcdn.com/ec.svg",
        },
        {
          englishName: "Egypt",
          arabicName: "مصر",
          region: "Africa",
          flag: "https://flagcdn.com/eg.svg",
        },
        {
          englishName: "El Salvador",
          arabicName: "السالوادور",
          region: "Americas",
          flag: "https://flagcdn.com/sv.svg",
        },
        {
          englishName: "Equatorial Guinea",
          arabicName: "گینه استوایی",
          region: "Africa",
          flag: "https://flagcdn.com/gq.svg",
        },
        {
          englishName: "Eritrea",
          arabicName: "اریتره",
          region: "Africa",
          flag: "https://flagcdn.com/er.svg",
        },
        {
          englishName: "Estonia",
          arabicName: "استونی",
          region: "Europe",
          flag: "https://flagcdn.com/ee.svg",
        },
        {
          englishName: "Ethiopia",
          arabicName: "اتیوپی",
          region: "Africa",
          flag: "https://flagcdn.com/et.svg",
        },
        {
          englishName: "Falkland Islands (Malvinas)",
          arabicName: "جزایر فالکلند",
          region: "Americas",
          flag: "https://flagcdn.com/fk.svg",
        },
        {
          englishName: "Faroe Islands",
          arabicName: "جزایر فارو",
          region: "Europe",
          flag: "https://flagcdn.com/fo.svg",
        },
        {
          englishName: "Fiji",
          arabicName: "فیجی",
          region: "Oceania",
          flag: "https://flagcdn.com/fj.svg",
        },
        {
          englishName: "Finland",
          arabicName: "فنلاند",
          region: "Europe",
          flag: "https://flagcdn.com/fi.svg",
        },
        {
          englishName: "France",
          arabicName: "فرانسه",
          region: "Europe",
          flag: "https://flagcdn.com/fr.svg",
        },
        {
          englishName: "French Guiana",
          arabicName: "گویان فرانسه",
          region: "Americas",
          flag: "https://flagcdn.com/gf.svg",
        },
        {
          englishName: "French Polynesia",
          arabicName: "پلی‌نزی فرانسه",
          region: "Oceania",
          flag: "https://flagcdn.com/pf.svg",
        },
        {
          englishName: "French Southern Territories",
          arabicName: "سرزمین‌های جنوبی و جنوبگانی فرانسه",
          region: "Africa",
          flag: "https://flagcdn.com/tf.svg",
        },
        {
          englishName: "Gabon",
          arabicName: "گابن",
          region: "Africa",
          flag: "https://flagcdn.com/ga.svg",
        },
        {
          englishName: "Gambia",
          arabicName: "گامبیا",
          region: "Africa",
          flag: "https://flagcdn.com/gm.svg",
        },
        {
          englishName: "Georgia",
          arabicName: "گرجستان",
          region: "Asia",
          flag: "https://flagcdn.com/ge.svg",
        },
        {
          englishName: "Germany",
          arabicName: "آلمان",
          region: "Europe",
          flag: "https://flagcdn.com/de.svg",
        },
        {
          englishName: "Ghana",
          arabicName: "غنا",
          region: "Africa",
          flag: "https://flagcdn.com/gh.svg",
        },
        {
          englishName: "Gibraltar",
          arabicName: "جبل‌طارق",
          region: "Europe",
          flag: "https://flagcdn.com/gi.svg",
        },
        {
          englishName: "Greece",
          arabicName: "یونان",
          region: "Europe",
          flag: "https://flagcdn.com/gr.svg",
        },
        {
          englishName: "Greenland",
          arabicName: "گرینلند",
          region: "Americas",
          flag: "https://flagcdn.com/gl.svg",
        },
        {
          englishName: "Grenada",
          arabicName: "گرنادا",
          region: "Americas",
          flag: "https://flagcdn.com/gd.svg",
        },
        {
          englishName: "Guadeloupe",
          arabicName: "جزیره گوادلوپ",
          region: "Americas",
          flag: "https://flagcdn.com/gp.svg",
        },
        {
          englishName: "Guam",
          arabicName: "گوام",
          region: "Oceania",
          flag: "https://flagcdn.com/gu.svg",
        },
        {
          englishName: "Guatemala",
          arabicName: "گواتمالا",
          region: "Americas",
          flag: "https://flagcdn.com/gt.svg",
        },
        {
          englishName: "Guernsey",
          arabicName: "گرنزی",
          region: "Europe",
          flag: "https://flagcdn.com/gg.svg",
        },
        {
          englishName: "Guinea",
          arabicName: "گینه",
          region: "Africa",
          flag: "https://flagcdn.com/gn.svg",
        },
        {
          englishName: "Guinea-Bissau",
          arabicName: "گینه بیسائو",
          region: "Africa",
          flag: "https://flagcdn.com/gw.svg",
        },
        {
          englishName: "Guyana",
          arabicName: "گویان",
          region: "Americas",
          flag: "https://flagcdn.com/gy.svg",
        },
        {
          englishName: "Haiti",
          arabicName: "هائیتی",
          region: "Americas",
          flag: "https://flagcdn.com/ht.svg",
        },
        {
          englishName: "Heard Island and McDonald Islands",
          arabicName: "جزیره هرد و جزایر مک‌دونالد",
          region: "Antarctic",
          flag: "https://flagcdn.com/hm.svg",
        },
        {
          englishName: "Vatican City",
          arabicName: "سریر مقدس",
          region: "Europe",
          flag: "https://flagcdn.com/va.svg",
        },
        {
          englishName: "Honduras",
          arabicName: "هندوراس",
          region: "Americas",
          flag: "https://flagcdn.com/hn.svg",
        },
        {
          englishName: "Hungary",
          arabicName: "مجارستان",
          region: "Europe",
          flag: "https://flagcdn.com/hu.svg",
        },
        {
          englishName: "Hong Kong",
          arabicName: "هنگ‌کنگ",
          region: "Asia",
          flag: "https://flagcdn.com/hk.svg",
        },
        {
          englishName: "Iceland",
          arabicName: "ایسلند",
          region: "Europe",
          flag: "https://flagcdn.com/is.svg",
        },
        {
          englishName: "India",
          arabicName: "هند",
          region: "Asia",
          flag: "https://flagcdn.com/in.svg",
        },
        {
          englishName: "Indonesia",
          arabicName: "اندونزی",
          region: "Asia",
          flag: "https://flagcdn.com/id.svg",
        },
        {
          englishName: "Ivory Coast",
          arabicName: "ساحل عاج",
          region: "Africa",
          flag: "https://flagcdn.com/ci.svg",
        },
        {
          englishName: "Iran (Islamic Republic of)",
          arabicName: "ایران",
          region: "Asia",
          flag: "https://flagcdn.com/ir.svg",
        },
        {
          englishName: "Iraq",
          arabicName: "عراق",
          region: "Asia",
          flag: "https://flagcdn.com/iq.svg",
        },
        {
          englishName: "Ireland",
          arabicName: "ایرلند",
          region: "Europe",
          flag: "https://flagcdn.com/ie.svg",
        },
        {
          englishName: "Isle of Man",
          arabicName: "جزیره من",
          region: "Europe",
          flag: "https://flagcdn.com/im.svg",
        },
        {
          englishName: "Israel",
          arabicName: "اسرائیل",
          region: "Asia",
          flag: "https://flagcdn.com/il.svg",
        },
        {
          englishName: "Italy",
          arabicName: "ایتالیا",
          region: "Europe",
          flag: "https://flagcdn.com/it.svg",
        },
        {
          englishName: "Jamaica",
          arabicName: "جامائیکا",
          region: "Americas",
          flag: "https://flagcdn.com/jm.svg",
        },
        {
          englishName: "Japan",
          arabicName: "ژاپن",
          region: "Asia",
          flag: "https://flagcdn.com/jp.svg",
        },
        {
          englishName: "Jersey",
          arabicName: "جرزی",
          region: "Europe",
          flag: "https://flagcdn.com/je.svg",
        },
        {
          englishName: "Jordan",
          arabicName: "اردن",
          region: "Asia",
          flag: "https://flagcdn.com/jo.svg",
        },
        {
          englishName: "Kazakhstan",
          arabicName: "قزاقستان",
          region: "Asia",
          flag: "https://flagcdn.com/kz.svg",
        },
        {
          englishName: "Kenya",
          arabicName: "کنیا",
          region: "Africa",
          flag: "https://flagcdn.com/ke.svg",
        },
        {
          englishName: "Kiribati",
          arabicName: "کیریباتی",
          region: "Oceania",
          flag: "https://flagcdn.com/ki.svg",
        },
        {
          englishName: "Kuwait",
          arabicName: "کویت",
          region: "Asia",
          flag: "https://flagcdn.com/kw.svg",
        },
        {
          englishName: "Kyrgyzstan",
          arabicName: "قرقیزستان",
          region: "Asia",
          flag: "https://flagcdn.com/kg.svg",
        },
        {
          englishName: "Lao People's Democratic Republic",
          arabicName: "لائوس",
          region: "Asia",
          flag: "https://flagcdn.com/la.svg",
        },
        {
          englishName: "Latvia",
          arabicName: "لتونی",
          region: "Europe",
          flag: "https://flagcdn.com/lv.svg",
        },
        {
          englishName: "Lebanon",
          arabicName: "لبنان",
          region: "Asia",
          flag: "https://flagcdn.com/lb.svg",
        },
        {
          englishName: "Lesotho",
          arabicName: "لسوتو",
          region: "Africa",
          flag: "https://flagcdn.com/ls.svg",
        },
        {
          englishName: "Liberia",
          arabicName: "لیبریا",
          region: "Africa",
          flag: "https://flagcdn.com/lr.svg",
        },
        {
          englishName: "Libya",
          arabicName: "لیبی",
          region: "Africa",
          flag: "https://flagcdn.com/ly.svg",
        },
        {
          englishName: "Liechtenstein",
          arabicName: "لیختن‌اشتاین",
          region: "Europe",
          flag: "https://flagcdn.com/li.svg",
        },
        {
          englishName: "Lithuania",
          arabicName: "لیتوانی",
          region: "Europe",
          flag: "https://flagcdn.com/lt.svg",
        },
        {
          englishName: "Luxembourg",
          arabicName: "لوکزامبورگ",
          region: "Europe",
          flag: "https://flagcdn.com/lu.svg",
        },
        {
          englishName: "Macao",
          arabicName: "مکائو",
          region: "Asia",
          flag: "https://flagcdn.com/mo.svg",
        },
        {
          englishName: "North Macedonia",
          region: "Europe",
          flag: "https://flagcdn.com/mk.svg",
        },
        {
          englishName: "Madagascar",
          arabicName: "ماداگاسکار",
          region: "Africa",
          flag: "https://flagcdn.com/mg.svg",
        },
        {
          englishName: "Malawi",
          arabicName: "مالاوی",
          region: "Africa",
          flag: "https://flagcdn.com/mw.svg",
        },
        {
          englishName: "Malaysia",
          arabicName: "مالزی",
          region: "Asia",
          flag: "https://flagcdn.com/my.svg",
        },
        {
          englishName: "Maldives",
          arabicName: "مالدیو",
          region: "Asia",
          flag: "https://flagcdn.com/mv.svg",
        },
        {
          englishName: "Mali",
          arabicName: "مالی",
          region: "Africa",
          flag: "https://flagcdn.com/ml.svg",
        },
        {
          englishName: "Malta",
          arabicName: "مالت",
          region: "Europe",
          flag: "https://flagcdn.com/mt.svg",
        },
        {
          englishName: "Marshall Islands",
          arabicName: "جزایر مارشال",
          region: "Oceania",
          flag: "https://flagcdn.com/mh.svg",
        },
        {
          englishName: "Martinique",
          arabicName: "مونتسرات",
          region: "Americas",
          flag: "https://flagcdn.com/mq.svg",
        },
        {
          englishName: "Mauritania",
          arabicName: "موریتانی",
          region: "Africa",
          flag: "https://flagcdn.com/mr.svg",
        },
        {
          englishName: "Mauritius",
          arabicName: "موریس",
          region: "Africa",
          flag: "https://flagcdn.com/mu.svg",
        },
        {
          englishName: "Mayotte",
          arabicName: "مایوت",
          region: "Africa",
          flag: "https://flagcdn.com/yt.svg",
        },
        {
          englishName: "Mexico",
          arabicName: "مکزیک",
          region: "Americas",
          flag: "https://flagcdn.com/mx.svg",
        },
        {
          englishName: "Micronesia (Federated States of)",
          arabicName: "ایالات فدرال میکرونزی",
          region: "Oceania",
          flag: "https://flagcdn.com/fm.svg",
        },
        {
          englishName: "Moldova (Republic of)",
          arabicName: "مولداوی",
          region: "Europe",
          flag: "https://flagcdn.com/md.svg",
        },
        {
          englishName: "Monaco",
          arabicName: "موناکو",
          region: "Europe",
          flag: "https://flagcdn.com/mc.svg",
        },
        {
          englishName: "Mongolia",
          arabicName: "مغولستان",
          region: "Asia",
          flag: "https://flagcdn.com/mn.svg",
        },
        {
          englishName: "Montenegro",
          arabicName: "مونته‌نگرو",
          region: "Europe",
          flag: "https://flagcdn.com/me.svg",
        },
        // {
        //   englishName: "Montserrat",
        //   arabicName: "مایوت",
        //   region: "Americas",
        //   flag: "https://flagcdn.com/ms.svg",
        // },
        {
          englishName: "Morocco",
          arabicName: "المغرب",
          region: "Africa",
          flag: "https://flagcdn.com/ma.svg",
        },
        {
          englishName: "Mozambique",
          arabicName: "موزامبیک",
          region: "Africa",
          flag: "https://flagcdn.com/mz.svg",
        },
        {
          englishName: "Myanmar",
          arabicName: "میانمار",
          region: "Asia",
          flag: "https://flagcdn.com/mm.svg",
        },
        {
          englishName: "Namibia",
          arabicName: "نامیبیا",
          region: "Africa",
          flag: "https://flagcdn.com/na.svg",
        },
        {
          englishName: "Nauru",
          arabicName: "نائورو",
          region: "Oceania",
          flag: "https://flagcdn.com/nr.svg",
        },
        {
          englishName: "Nepal",
          arabicName: "نپال",
          region: "Asia",
          flag: "https://flagcdn.com/np.svg",
        },
        {
          englishName: "Netherlands",
          arabicName: "پادشاهی هلند",
          region: "Europe",
          flag: "https://flagcdn.com/nl.svg",
        },
        {
          englishName: "New Caledonia",
          arabicName: "کالدونیای جدید",
          region: "Oceania",
          flag: "https://flagcdn.com/nc.svg",
        },
        {
          englishName: "New Zealand",
          arabicName: "نیوزیلند",
          region: "Oceania",
          flag: "https://flagcdn.com/nz.svg",
        },
        {
          englishName: "Nicaragua",
          arabicName: "نیکاراگوئه",
          region: "Americas",
          flag: "https://flagcdn.com/ni.svg",
        },
        {
          englishName: "Niger",
          arabicName: "نیجر",
          region: "Africa",
          flag: "https://flagcdn.com/ne.svg",
        },
        {
          englishName: "Nigeria",
          arabicName: "نیجریه",
          region: "Africa",
          flag: "https://flagcdn.com/ng.svg",
        },
        {
          englishName: "Niue",
          arabicName: "نیووی",
          region: "Oceania",
          flag: "https://flagcdn.com/nu.svg",
        },
        {
          englishName: "Norfolk Island",
          arabicName: "جزیره نورفک",
          region: "Oceania",
          flag: "https://flagcdn.com/nf.svg",
        },
        {
          englishName: "Korea (Democratic People's Republic of)",
          arabicName: "کره جنوبی",
          region: "Asia",
          flag: "https://flagcdn.com/kp.svg",
        },
        {
          englishName: "Northern Mariana Islands",
          arabicName: "جزایر ماریانای شمالی",
          region: "Oceania",
          flag: "https://flagcdn.com/mp.svg",
        },
        {
          englishName: "Norway",
          arabicName: "نروژ",
          region: "Europe",
          flag: "https://flagcdn.com/no.svg",
        },
        {
          englishName: "Oman",
          arabicName: "عمان",
          region: "Asia",
          flag: "https://flagcdn.com/om.svg",
        },
        {
          englishName: "Pakistan",
          arabicName: "پاکستان",
          region: "Asia",
          flag: "https://flagcdn.com/pk.svg",
        },
        {
          englishName: "Palau",
          arabicName: "پالائو",
          region: "Oceania",
          flag: "https://flagcdn.com/pw.svg",
        },
        {
          englishName: "Palestine, State of",
          arabicName: "فلسطین",
          region: "Asia",
          flag: "https://flagcdn.com/ps.svg",
        },
        {
          englishName: "Panama",
          arabicName: "پاناما",
          region: "Americas",
          flag: "https://flagcdn.com/pa.svg",
        },
        {
          englishName: "Papua New Guinea",
          arabicName: "پاپوآ گینه نو",
          region: "Oceania",
          flag: "https://flagcdn.com/pg.svg",
        },
        {
          englishName: "Paraguay",
          arabicName: "پاراگوئه",
          region: "Americas",
          flag: "https://flagcdn.com/py.svg",
        },
        {
          englishName: "Peru",
          arabicName: "پرو",
          region: "Americas",
          flag: "https://flagcdn.com/pe.svg",
        },
        {
          englishName: "Philippines",
          arabicName: "جزایر الندفیلیپین",
          region: "Asia",
          flag: "https://flagcdn.com/ph.svg",
        },
        {
          englishName: "Pitcairn",
          arabicName: "پیتکرن",
          region: "Oceania",
          flag: "https://flagcdn.com/pn.svg",
        },
        {
          englishName: "Poland",
          arabicName: "لهستان",
          region: "Europe",
          flag: "https://flagcdn.com/pl.svg",
        },
        {
          englishName: "Portugal",
          arabicName: "پرتغال",
          region: "Europe",
          flag: "https://flagcdn.com/pt.svg",
        },
        {
          englishName: "Puerto Rico",
          arabicName: "پورتو ریکو",
          region: "Americas",
          flag: "https://flagcdn.com/pr.svg",
        },
        {
          englishName: "Qatar",
          arabicName: "قطر",
          region: "Asia",
          flag: "https://flagcdn.com/qa.svg",
        },
        {
          englishName: "Republic of Kosovo",
          arabicName: "کوزوو",
          region: "Europe",
          flag: "https://flagcdn.com/xk.svg",
        },
        {
          englishName: "Réunion",
          arabicName: "رئونیون",
          region: "Africa",
          flag: "https://flagcdn.com/re.svg",
        },
        {
          englishName: "Romania",
          arabicName: "رومانی",
          region: "Europe",
          flag: "https://flagcdn.com/ro.svg",
        },
        {
          englishName: "Russian Federation",
          arabicName: "روسیه",
          region: "Europe",
          flag: "https://flagcdn.com/ru.svg",
        },
        {
          englishName: "Rwanda",
          arabicName: "رواندا",
          region: "Africa",
          flag: "https://flagcdn.com/rw.svg",
        },
        {
          englishName: "Saint Barthélemy",
          arabicName: "سن-بارتلمی",
          region: "Americas",
          flag: "https://flagcdn.com/bl.svg",
        },
        {
          englishName: "Saint Helena, Ascension and Tristan da Cunha",
          arabicName: "سنت هلنا، اسنشن و تریستان دا کونا",
          region: "Africa",
          flag: "https://flagcdn.com/sh.svg",
        },
        {
          englishName: "Saint Kitts and Nevis",
          arabicName: "سنت کیتس و نویس",
          region: "Americas",
          flag: "https://flagcdn.com/kn.svg",
        },
        {
          englishName: "Saint Lucia",
          arabicName: "سنت لوسیا",
          region: "Americas",
          flag: "https://flagcdn.com/lc.svg",
        },
        // {
        //   englishName: "Saint Martin (French part)",
        //   arabicName: "سینت مارتن",
        //   region: "Americas",
        //   flag: "https://flagcdn.com/mf.svg",
        // },
        {
          englishName: "Saint Pierre and Miquelon",
          arabicName: "سن پیر و میکلن",
          region: "Americas",
          flag: "https://flagcdn.com/pm.svg",
        },
        {
          englishName: "Saint Vincent and the Grenadines",
          arabicName: "سنت وینسنت و گرنادین‌ها",
          region: "Americas",
          flag: "https://flagcdn.com/vc.svg",
        },
        {
          englishName: "Samoa",
          arabicName: "ساموآ",
          region: "Oceania",
          flag: "https://flagcdn.com/ws.svg",
        },
        {
          englishName: "San Marino",
          arabicName: "سان مارینو",
          region: "Europe",
          flag: "https://flagcdn.com/sm.svg",
        },
        {
          englishName: "Sao Tome and Principe",
          arabicName: "کواترو دو فرویرو",
          region: "Africa",
          flag: "https://flagcdn.com/st.svg",
        },
        {
          englishName: "Saudi Arabia",
          arabicName: "عربستان سعودی",
          region: "Asia",
          flag: "https://flagcdn.com/sa.svg",
        },
        {
          englishName: "Senegal",
          arabicName: "سنگال",
          region: "Africa",
          flag: "https://flagcdn.com/sn.svg",
        },
        {
          englishName: "Serbia",
          arabicName: "صربستان",
          region: "Europe",
          flag: "https://flagcdn.com/rs.svg",
        },
        {
          englishName: "Seychelles",
          arabicName: "سیشل",
          region: "Africa",
          flag: "https://flagcdn.com/sc.svg",
        },
        {
          englishName: "Sierra Leone",
          arabicName: "سیرالئون",
          region: "Africa",
          flag: "https://flagcdn.com/sl.svg",
        },
        {
          englishName: "Singapore",
          arabicName: "سنگاپور",
          region: "Asia",
          flag: "https://flagcdn.com/sg.svg",
        },
        {
          englishName: "Sint Maarten (Dutch part)",
          arabicName: "سینت مارتن",
          region: "Americas",
          flag: "https://flagcdn.com/sx.svg",
        },
        {
          englishName: "Slovakia",
          arabicName: "اسلواکی",
          region: "Europe",
          flag: "https://flagcdn.com/sk.svg",
        },
        {
          englishName: "Slovenia",
          arabicName: "اسلوونی",
          region: "Europe",
          flag: "https://flagcdn.com/si.svg",
        },
        {
          englishName: "Solomon Islands",
          arabicName: "جزایر سلیمان",
          region: "Oceania",
          flag: "https://flagcdn.com/sb.svg",
        },
        {
          englishName: "Somalia",
          arabicName: "سومالی",
          region: "Africa",
          flag: "https://flagcdn.com/so.svg",
        },
        {
          englishName: "South Africa",
          arabicName: "آفریقای جنوبی",
          region: "Africa",
          flag: "https://flagcdn.com/za.svg",
        },
        {
          englishName: "South Georgia and the South Sandwich Islands",
          arabicName: "جزایر جورجیای جنوبی و ساندویچ جنوبی",
          region: "Americas",
          flag: "https://flagcdn.com/gs.svg",
        },
        {
          englishName: "Korea (Republic of)",
          arabicName: "کره شمالی",
          region: "Asia",
          flag: "https://flagcdn.com/kr.svg",
        },
        {
          englishName: "Spain",
          arabicName: "اسپانیا",
          region: "Europe",
          flag: "https://flagcdn.com/es.svg",
        },
        {
          englishName: "Sri Lanka",
          arabicName: "سری‌لانکا",
          region: "Asia",
          flag: "https://flagcdn.com/lk.svg",
        },
        {
          englishName: "Sudan",
          arabicName: "سودان",
          region: "Africa",
          flag: "https://flagcdn.com/sd.svg",
        },
        {
          englishName: "South Sudan",
          arabicName: "سودان جنوبی",
          region: "Africa",
          flag: "https://flagcdn.com/ss.svg",
        },
        {
          englishName: "Suriname",
          arabicName: "سورینام",
          region: "Americas",
          flag: "https://flagcdn.com/sr.svg",
        },
        {
          englishName: "Svalbard and Jan Mayen",
          arabicName: "سوالبارد و یان ماین",
          region: "Europe",
          flag: "https://flagcdn.com/sj.svg",
        },
        {
          englishName: "Swaziland",
          arabicName: "سوازیلند",
          region: "Africa",
          flag: "https://flagcdn.com/sz.svg",
        },
        {
          englishName: "Sweden",
          arabicName: "سوئد",
          region: "Europe",
          flag: "https://flagcdn.com/se.svg",
        },
        {
          englishName: "Switzerland",
          arabicName: "سوئیس",
          region: "Europe",
          flag: "https://flagcdn.com/ch.svg",
        },
        {
          englishName: "Syrian Arab Republic",
          arabicName: "سوریه",
          region: "Asia",
          flag: "https://flagcdn.com/sy.svg",
        },
        {
          englishName: "Taiwan",
          arabicName: "تایوان",
          region: "Asia",
          flag: "https://flagcdn.com/tw.svg",
        },
        {
          englishName: "Tajikistan",
          arabicName: "تاجیکستان",
          region: "Asia",
          flag: "https://flagcdn.com/tj.svg",
        },
        {
          englishName: "Tanzania, United Republic of",
          arabicName: "تانزانیا",
          region: "Africa",
          flag: "https://flagcdn.com/tz.svg",
        },
        {
          englishName: "Thailand",
          arabicName: "تایلند",
          region: "Asia",
          flag: "https://flagcdn.com/th.svg",
        },
        {
          englishName: "Timor-Leste",
          arabicName: "تیمور شرقی",
          region: "Asia",
          flag: "https://flagcdn.com/tl.svg",
        },
        {
          englishName: "Togo",
          arabicName: "توگو",
          region: "Africa",
          flag: "https://flagcdn.com/tg.svg",
        },
        {
          englishName: "Tokelau",
          arabicName: "توکلائو",
          region: "Oceania",
          flag: "https://flagcdn.com/tk.svg",
        },
        {
          englishName: "Tonga",
          arabicName: "تونگا",
          region: "Oceania",
          flag: "https://flagcdn.com/to.svg",
        },
        {
          englishName: "Trinidad and Tobago",
          arabicName: "ترینیداد و توباگو",
          region: "Americas",
          flag: "https://flagcdn.com/tt.svg",
        },
        {
          englishName: "Tunisia",
          arabicName: "تونس",
          region: "Africa",
          flag: "https://flagcdn.com/tn.svg",
        },
        {
          englishName: "Turkey",
          arabicName: "ترکیه",
          region: "Asia",
          flag: "https://flagcdn.com/tr.svg",
        },
        {
          englishName: "Turkmenistan",
          arabicName: "ترکمنستان",
          region: "Asia",
          flag: "https://flagcdn.com/tm.svg",
        },
        {
          englishName: "Turks and Caicos Islands",
          arabicName: "جزایر تورکس و کایکوس",
          region: "Americas",
          flag: "https://flagcdn.com/tc.svg",
        },
        {
          englishName: "Tuvalu",
          arabicName: "تووالو",
          region: "Oceania",
          flag: "https://flagcdn.com/tv.svg",
        },
        {
          englishName: "Uganda",
          arabicName: "اوگاندا",
          region: "Africa",
          flag: "https://flagcdn.com/ug.svg",
        },
        {
          englishName: "Ukraine",
          arabicName: "وکراین",
          region: "Europe",
          flag: "https://flagcdn.com/ua.svg",
        },
        {
          englishName: "United Arab Emirates",
          arabicName: "امارات متحده عربی",
          region: "Asia",
          flag: "https://flagcdn.com/ae.svg",
        },
        {
          englishName: "United Kingdom of Great Britain and Northern Ireland",
          arabicName: "بریتانیای کبیر و ایرلند شمالی",
          region: "Europe",
          flag: "https://flagcdn.com/gb.svg",
        },
        {
          englishName: "United States of America",
          arabicName: "ایالات متحده آمریکا",
          region: "Americas",
          flag: "https://flagcdn.com/us.svg",
        },
        {
          englishName: "Uruguay",
          arabicName: "اروگوئه",
          region: "Americas",
          flag: "https://flagcdn.com/uy.svg",
        },
        {
          englishName: "Uzbekistan",
          arabicName: "ازبکستان",
          region: "Asia",
          flag: "https://flagcdn.com/uz.svg",
        },
        {
          englishName: "Vanuatu",
          arabicName: "وانواتو",
          region: "Oceania",
          flag: "https://flagcdn.com/vu.svg",
        },
        {
          englishName: "Venezuela (Bolivarian Republic of)",
          arabicName: "ونزوئلا",
          region: "Americas",
          flag: "https://flagcdn.com/ve.svg",
        },
        {
          englishName: "Vietnam",
          arabicName: "ویتنام",
          region: "Asia",
          flag: "https://flagcdn.com/vn.svg",
        },
        {
          englishName: "Wallis and Futuna",
          arabicName: "والیس و فوتونا",
          region: "Oceania",
          flag: "https://flagcdn.com/wf.svg",
        },
        {
          englishName: "Western Sahara",
          arabicName: "جمهوری دموکراتیک عربی صحرا",
          region: "Africa",
          flag: "https://flagcdn.com/eh.svg",
        },
        {
          englishName: "Yemen",
          arabicName: "یمن",
          region: "Asia",
          flag: "https://flagcdn.com/ye.svg",
        },
        {
          englishName: "Zambia",
          arabicName: "زامبیا",
          region: "Africa",
          flag: "https://flagcdn.com/zm.svg",
        },
        {
          englishName: "Zimbabwe",
          arabicName: "زیمباوه",
          region: "Africa",
          flag: "https://flagcdn.com/zw.svg",
        },
      ]
    }
  }
}
