export default {
  data() {
    return {
      cities: [
        {
          id: "1",
          governorate_id: "1",
          arabic: "15 مايو",
          english: "15 May",
        },
        {
          id: "2",
          governorate_id: "1",
          arabic: "الازبكية",
          english: "Al Azbakeyah",
        },
        {
          id: "3",
          governorate_id: "1",
          arabic: "البساتين",
          english: "Al Basatin",
        },
        {
          id: "4",
          governorate_id: "1",
          arabic: "التبين",
          english: "Tebin",
        },
        {
          id: "5",
          governorate_id: "1",
          arabic: "الخليفة",
          english: "El-Khalifa",
        },
        {
          id: "6",
          governorate_id: "1",
          arabic: "الدراسة",
          english: "El darrasa",
        },
        {
          id: "7",
          governorate_id: "1",
          arabic: "الدرب الاحمر",
          english: "Aldarb Alahmar",
        },
        {
          id: "8",
          governorate_id: "1",
          arabic: "الزاوية الحمراء",
          english: "Zawya al-Hamra",
        },
        {
          id: "9",
          governorate_id: "1",
          arabic: "الزيتون",
          english: "El-Zaytoun",
        },
        {
          id: "10",
          governorate_id: "1",
          arabic: "الساحل",
          english: "Sahel",
        },
        {
          id: "11",
          governorate_id: "1",
          arabic: "السلام",
          english: "El Salam",
        },
        {
          id: "12",
          governorate_id: "1",
          arabic: "السيدة زينب",
          english: "Sayeda Zeinab",
        },
        {
          id: "13",
          governorate_id: "1",
          arabic: "الشرابية",
          english: "El Sharabeya",
        },
        {
          id: "14",
          governorate_id: "1",
          arabic: "مدينة الشروق",
          english: "Shorouk",
        },
        {
          id: "15",
          governorate_id: "1",
          arabic: "الظاهر",
          english: "El Daher",
        },
        {
          id: "16",
          governorate_id: "1",
          arabic: "العتبة",
          english: "Ataba",
        },
        {
          id: "17",
          governorate_id: "1",
          arabic: "القاهرة الجديدة",
          english: "New Cairo",
        },
        {
          id: "18",
          governorate_id: "1",
          arabic: "المرج",
          english: "El Marg",
        },
        {
          id: "19",
          governorate_id: "1",
          arabic: "عزبة النخل",
          english: "Ezbet el Nakhl",
        },
        {
          id: "20",
          governorate_id: "1",
          arabic: "المطرية",
          english: "Matareya",
        },
        {
          id: "21",
          governorate_id: "1",
          arabic: "المعادى",
          english: "Maadi",
        },
        {
          id: "22",
          governorate_id: "1",
          arabic: "المعصرة",
          english: "Maasara",
        },
        {
          id: "23",
          governorate_id: "1",
          arabic: "المقطم",
          english: "Mokattam",
        },
        {
          id: "24",
          governorate_id: "1",
          arabic: "المنيل",
          english: "Manyal",
        },
        {
          id: "25",
          governorate_id: "1",
          arabic: "الموسكى",
          english: "Mosky",
        },
        {
          id: "26",
          governorate_id: "1",
          arabic: "النزهة",
          english: "Nozha",
        },
        {
          id: "27",
          governorate_id: "1",
          arabic: "الوايلى",
          english: "Waily",
        },
        {
          id: "28",
          governorate_id: "1",
          arabic: "باب الشعرية",
          english: "Bab al-Shereia",
        },
        {
          id: "29",
          governorate_id: "1",
          arabic: "بولاق",
          english: "Bolaq",
        },
        {
          id: "30",
          governorate_id: "1",
          arabic: "جاردن سيتى",
          english: "Garden City",
        },
        {
          id: "31",
          governorate_id: "1",
          arabic: "حدائق القبة",
          english: "Hadayek El-Kobba",
        },
        {
          id: "32",
          governorate_id: "1",
          arabic: "حلوان",
          english: "Helwan",
        },
        {
          id: "33",
          governorate_id: "1",
          arabic: "دار السلام",
          english: "Dar Al Salam",
        },
        {
          id: "34",
          governorate_id: "1",
          arabic: "شبرا",
          english: "Shubra",
        },
        {
          id: "35",
          governorate_id: "1",
          arabic: "طره",
          english: "Tura",
        },
        {
          id: "36",
          governorate_id: "1",
          arabic: "عابدين",
          english: "Abdeen",
        },
        {
          id: "37",
          governorate_id: "1",
          arabic: "عباسية",
          english: "Abaseya",
        },
        {
          id: "38",
          governorate_id: "1",
          arabic: "عين شمس",
          english: "Ain Shams",
        },
        {
          id: "39",
          governorate_id: "1",
          arabic: "مدينة نصر",
          english: "Nasr City",
        },
        {
          id: "40",
          governorate_id: "1",
          arabic: "مصر الجديدة",
          english: "New Heliopolis",
        },
        {
          id: "41",
          governorate_id: "1",
          arabic: "مصر القديمة",
          english: "Masr Al Qadima",
        },
        {
          id: "42",
          governorate_id: "1",
          arabic: "منشية ناصر",
          english: "Mansheya Nasir",
        },
        {
          id: "43",
          governorate_id: "1",
          arabic: "مدينة بدر",
          english: "Badr City",
        },
        {
          id: "44",
          governorate_id: "1",
          arabic: "مدينة العبور",
          english: "Obour City",
        },
        {
          id: "45",
          governorate_id: "1",
          arabic: "وسط البلد",
          english: "Cairo Downtown",
        },
        {
          id: "46",
          governorate_id: "1",
          arabic: "الزمالك",
          english: "Zamalek",
        },
        {
          id: "47",
          governorate_id: "1",
          arabic: "قصر النيل",
          english: "Kasr El Nile",
        },
        {
          id: "48",
          governorate_id: "1",
          arabic: "الرحاب",
          english: "Rehab",
        },
        {
          id: "49",
          governorate_id: "1",
          arabic: "القطامية",
          english: "Katameya",
        },
        {
          id: "50",
          governorate_id: "1",
          arabic: "مدينتي",
          english: "Madinty",
        },
        {
          id: "51",
          governorate_id: "1",
          arabic: "روض الفرج",
          english: "Rod Alfarag",
        },
        {
          id: "52",
          governorate_id: "1",
          arabic: "شيراتون",
          english: "Sheraton",
        },
        {
          id: "53",
          governorate_id: "1",
          arabic: "الجمالية",
          english: "El-Gamaleya",
        },
        {
          id: "54",
          governorate_id: "1",
          arabic: "العاشر من رمضان",
          english: "10th of Ramadan City",
        },
        {
          id: "55",
          governorate_id: "1",
          arabic: "الحلمية",
          english: "Helmeyat Alzaytoun",
        },
        {
          id: "56",
          governorate_id: "1",
          arabic: "النزهة الجديدة",
          english: "New Nozha",
        },
        {
          id: "57",
          governorate_id: "1",
          arabic: "العاصمة الإدارية",
          english: "Capital New",
        },
        {
          id: "58",
          governorate_id: "2",
          arabic: "الجيزة",
          english: "Giza",
        },
        {
          id: "59",
          governorate_id: "2",
          arabic: "السادس من أكتوبر",
          english: "Sixth of October",
        },
        {
          id: "60",
          governorate_id: "2",
          arabic: "الشيخ زايد",
          english: "Cheikh Zayed",
        },
        {
          id: "61",
          governorate_id: "2",
          arabic: "الحوامدية",
          english: "Hawamdiyah",
        },
        {
          id: "62",
          governorate_id: "2",
          arabic: "البدرشين",
          english: "Al Badrasheen",
        },
        {
          id: "63",
          governorate_id: "2",
          arabic: "الصف",
          english: "Saf",
        },
        {
          id: "64",
          governorate_id: "2",
          arabic: "أطفيح",
          english: "Atfih",
        },
        {
          id: "65",
          governorate_id: "2",
          arabic: "العياط",
          english: "Al Ayat",
        },
        {
          id: "66",
          governorate_id: "2",
          arabic: "الباويطي",
          english: "Al-Bawaiti",
        },
        {
          id: "67",
          governorate_id: "2",
          arabic: "منشأة القناطر",
          english: "ManshiyetAl Qanater",
        },
        {
          id: "68",
          governorate_id: "2",
          arabic: "أوسيم",
          english: "Oaseem",
        },
        {
          id: "69",
          governorate_id: "2",
          arabic: "كرداسة",
          english: "Kerdasa",
        },
        {
          id: "70",
          governorate_id: "2",
          arabic: "أبو النمرس",
          english: "Abu Nomros",
        },
        {
          id: "71",
          governorate_id: "2",
          arabic: "كفر غطاطي",
          english: "Kafr Ghati",
        },
        {
          id: "72",
          governorate_id: "2",
          arabic: "منشأة البكاري",
          english: "Manshiyet Al Bakari",
        },
        {
          id: "73",
          governorate_id: "2",
          arabic: "الدقى",
          english: "Dokki",
        },
        {
          id: "74",
          governorate_id: "2",
          arabic: "العجوزة",
          english: "Agouza",
        },
        {
          id: "75",
          governorate_id: "2",
          arabic: "الهرم",
          english: "Haram",
        },
        {
          id: "76",
          governorate_id: "2",
          arabic: "الوراق",
          english: "Warraq",
        },
        {
          id: "77",
          governorate_id: "2",
          arabic: "امبابة",
          english: "Imbaba",
        },
        {
          id: "78",
          governorate_id: "2",
          arabic: "بولاق الدكرور",
          english: "Boulaq Dakrour",
        },
        {
          id: "79",
          governorate_id: "2",
          arabic: "الواحات البحرية",
          english: "Al Wahat Al Baharia",
        },
        {
          id: "80",
          governorate_id: "2",
          arabic: "العمرانية",
          english: "Omraneya",
        },
        {
          id: "81",
          governorate_id: "2",
          arabic: "المنيب",
          english: "Moneeb",
        },
        {
          id: "82",
          governorate_id: "2",
          arabic: "بين السرايات",
          english: "Bin Alsarayat",
        },
        {
          id: "83",
          governorate_id: "2",
          arabic: "الكيت كات",
          english: "Kit Kat",
        },
        {
          id: "84",
          governorate_id: "2",
          arabic: "المهندسين",
          english: "Mohandessin",
        },
        {
          id: "85",
          governorate_id: "2",
          arabic: "فيصل",
          english: "Faisal",
        },
        {
          id: "86",
          governorate_id: "2",
          arabic: "أبو رواش",
          english: "Abu Rawash",
        },
        {
          id: "87",
          governorate_id: "2",
          arabic: "حدائق الأهرام",
          english: "Hadayek Alahram",
        },
        {
          id: "88",
          governorate_id: "2",
          arabic: "الحرانية",
          english: "Haraneya",
        },
        {
          id: "89",
          governorate_id: "2",
          arabic: "حدائق اكتوبر",
          english: "Hadayek October",
        },
        {
          id: "90",
          governorate_id: "2",
          arabic: "صفط اللبن",
          english: "Saft Allaban",
        },
        {
          id: "91",
          governorate_id: "2",
          arabic: "القرية الذكية",
          english: "Smart Village",
        },
        {
          id: "92",
          governorate_id: "2",
          arabic: "ارض اللواء",
          english: "Ard Ellwaa",
        },
        {
          id: "93",
          governorate_id: "3",
          arabic: "ابو قير",
          english: "Abu Qir",
        },
        {
          id: "94",
          governorate_id: "3",
          arabic: "الابراهيمية",
          english: "Al Ibrahimeyah",
        },
        {
          id: "95",
          governorate_id: "3",
          arabic: "الأزاريطة",
          english: "Azarita",
        },
        {
          id: "96",
          governorate_id: "3",
          arabic: "الانفوشى",
          english: "Anfoushi",
        },
        {
          id: "97",
          governorate_id: "3",
          arabic: "الدخيلة",
          english: "Dekheila",
        },
        {
          id: "98",
          governorate_id: "3",
          arabic: "السيوف",
          english: "El Soyof",
        },
        {
          id: "99",
          governorate_id: "3",
          arabic: "العامرية",
          english: "Ameria",
        },
        {
          id: "100",
          governorate_id: "3",
          arabic: "اللبان",
          english: "El Labban",
        },
        {
          id: "101",
          governorate_id: "3",
          arabic: "المفروزة",
          english: "Al Mafrouza",
        },
        {
          id: "102",
          governorate_id: "3",
          arabic: "المنتزه",
          english: "El Montaza",
        },
        {
          id: "103",
          governorate_id: "3",
          arabic: "المنشية",
          english: "Mansheya",
        },
        {
          id: "104",
          governorate_id: "3",
          arabic: "الناصرية",
          english: "Naseria",
        },
        {
          id: "105",
          governorate_id: "3",
          arabic: "امبروزو",
          english: "Ambrozo",
        },
        {
          id: "106",
          governorate_id: "3",
          arabic: "باب شرق",
          english: "Bab Sharq",
        },
        {
          id: "107",
          governorate_id: "3",
          arabic: "برج العرب",
          english: "Bourj Alarab",
        },
        {
          id: "108",
          governorate_id: "3",
          arabic: "ستانلى",
          english: "Stanley",
        },
        {
          id: "109",
          governorate_id: "3",
          arabic: "سموحة",
          english: "Smouha",
        },
        {
          id: "110",
          governorate_id: "3",
          arabic: "سيدى بشر",
          english: "Sidi Bishr",
        },
        {
          id: "111",
          governorate_id: "3",
          arabic: "شدس",
          english: "Shads",
        },
        {
          id: "112",
          governorate_id: "3",
          arabic: "غيط العنب",
          english: "Gheet Alenab",
        },
        {
          id: "113",
          governorate_id: "3",
          arabic: "فلمينج",
          english: "Fleming",
        },
        {
          id: "114",
          governorate_id: "3",
          arabic: "فيكتوريا",
          english: "Victoria",
        },
        {
          id: "115",
          governorate_id: "3",
          arabic: "كامب شيزار",
          english: "Camp Shizar",
        },
        {
          id: "116",
          governorate_id: "3",
          arabic: "كرموز",
          english: "Karmooz",
        },
        {
          id: "117",
          governorate_id: "3",
          arabic: "محطة الرمل",
          english: "Mahta Alraml",
        },
        {
          id: "118",
          governorate_id: "3",
          arabic: "مينا البصل",
          english: "Mina El-Basal",
        },
        {
          id: "119",
          governorate_id: "3",
          arabic: "العصافرة",
          english: "Asafra",
        },
        {
          id: "120",
          governorate_id: "3",
          arabic: "العجمي",
          english: "Agamy",
        },
        {
          id: "121",
          governorate_id: "3",
          arabic: "بكوس",
          english: "Bakos",
        },
        {
          id: "122",
          governorate_id: "3",
          arabic: "بولكلي",
          english: "Boulkly",
        },
        {
          id: "123",
          governorate_id: "3",
          arabic: "كليوباترا",
          english: "Cleopatra",
        },
        {
          id: "124",
          governorate_id: "3",
          arabic: "جليم",
          english: "Glim",
        },
        {
          id: "125",
          governorate_id: "3",
          arabic: "المعمورة",
          english: "Al Mamurah",
        },
        {
          id: "126",
          governorate_id: "3",
          arabic: "المندرة",
          english: "Al Mandara",
        },
        {
          id: "127",
          governorate_id: "3",
          arabic: "محرم بك",
          english: "Moharam Bek",
        },
        {
          id: "128",
          governorate_id: "3",
          arabic: "الشاطبي",
          english: "Elshatby",
        },
        {
          id: "129",
          governorate_id: "3",
          arabic: "سيدي جابر",
          english: "Sidi Gaber",
        },
        {
          id: "130",
          governorate_id: "3",
          arabic: "الساحل الشمالي",
          english: "North Coast-sahel",
        },
        {
          id: "131",
          governorate_id: "3",
          arabic: "الحضرة",
          english: "Alhadra",
        },
        {
          id: "132",
          governorate_id: "3",
          arabic: "العطارين",
          english: "Alattarin",
        },
        {
          id: "133",
          governorate_id: "3",
          arabic: "سيدي كرير",
          english: "Sidi Kerir",
        },
        {
          id: "134",
          governorate_id: "3",
          arabic: "الجمرك",
          english: "Elgomrok",
        },
        {
          id: "135",
          governorate_id: "3",
          arabic: "المكس",
          english: "Al Max",
        },
        {
          id: "136",
          governorate_id: "3",
          arabic: "مارينا",
          english: "Marina",
        },
        {
          id: "137",
          governorate_id: "4",
          arabic: "المنصورة",
          english: "Mansoura",
        },
        {
          id: "138",
          governorate_id: "4",
          arabic: "طلخا",
          english: "Talkha",
        },
        {
          id: "139",
          governorate_id: "4",
          arabic: "ميت غمر",
          english: "Mitt Ghamr",
        },
        {
          id: "140",
          governorate_id: "4",
          arabic: "دكرنس",
          english: "Dekernes",
        },
        {
          id: "141",
          governorate_id: "4",
          arabic: "أجا",
          english: "Aga",
        },
        {
          id: "142",
          governorate_id: "4",
          arabic: "منية النصر",
          english: "Menia El Nasr",
        },
        {
          id: "143",
          governorate_id: "4",
          arabic: "السنبلاوين",
          english: "Sinbillawin",
        },
        {
          id: "144",
          governorate_id: "4",
          arabic: "الكردي",
          english: "El Kurdi",
        },
        {
          id: "145",
          governorate_id: "4",
          arabic: "بني عبيد",
          english: "Bani Ubaid",
        },
        {
          id: "146",
          governorate_id: "4",
          arabic: "المنزلة",
          english: "Al Manzala",
        },
        {
          id: "147",
          governorate_id: "4",
          arabic: "تمي الأمديد",
          english: "tami al'amdid",
        },
        {
          id: "148",
          governorate_id: "4",
          arabic: "الجمالية",
          english: "aljamalia",
        },
        {
          id: "149",
          governorate_id: "4",
          arabic: "شربين",
          english: "Sherbin",
        },
        {
          id: "150",
          governorate_id: "4",
          arabic: "المطرية",
          english: "Mataria",
        },
        {
          id: "151",
          governorate_id: "4",
          arabic: "بلقاس",
          english: "Belqas",
        },
        {
          id: "152",
          governorate_id: "4",
          arabic: "ميت سلسيل",
          english: "Meet Salsil",
        },
        {
          id: "153",
          governorate_id: "4",
          arabic: "جمصة",
          english: "Gamasa",
        },
        {
          id: "154",
          governorate_id: "4",
          arabic: "محلة دمنة",
          english: "Mahalat Damana",
        },
        {
          id: "155",
          governorate_id: "4",
          arabic: "نبروه",
          english: "Nabroh",
        },
        {
          id: "156",
          governorate_id: "5",
          arabic: "الغردقة",
          english: "Hurghada",
        },
        {
          id: "157",
          governorate_id: "5",
          arabic: "رأس غارب",
          english: "Ras Ghareb",
        },
        {
          id: "158",
          governorate_id: "5",
          arabic: "سفاجا",
          english: "Safaga",
        },
        {
          id: "159",
          governorate_id: "5",
          arabic: "القصير",
          english: "El Qusiar",
        },
        {
          id: "160",
          governorate_id: "5",
          arabic: "مرسى علم",
          english: "Marsa Alam",
        },
        {
          id: "161",
          governorate_id: "5",
          arabic: "الشلاتين",
          english: "Shalatin",
        },
        {
          id: "162",
          governorate_id: "5",
          arabic: "حلايب",
          english: "Halaib",
        },
        {
          id: "163",
          governorate_id: "5",
          arabic: "الدهار",
          english: "Aldahar",
        },
        {
          id: "164",
          governorate_id: "6",
          arabic: "دمنهور",
          english: "Damanhour",
        },
        {
          id: "165",
          governorate_id: "6",
          arabic: "كفر الدوار",
          english: "Kafr El Dawar",
        },
        {
          id: "166",
          governorate_id: "6",
          arabic: "رشيد",
          english: "Rashid",
        },
        {
          id: "167",
          governorate_id: "6",
          arabic: "إدكو",
          english: "Edco",
        },
        {
          id: "168",
          governorate_id: "6",
          arabic: "أبو المطامير",
          english: "Abu al-Matamir",
        },
        {
          id: "169",
          governorate_id: "6",
          arabic: "أبو حمص",
          english: "Abu Homs",
        },
        {
          id: "170",
          governorate_id: "6",
          arabic: "الدلنجات",
          english: "Delengat",
        },
        {
          id: "171",
          governorate_id: "6",
          arabic: "المحمودية",
          english: "Mahmoudiyah",
        },
        {
          id: "172",
          governorate_id: "6",
          arabic: "الرحمانية",
          english: "Rahmaniyah",
        },
        {
          id: "173",
          governorate_id: "6",
          arabic: "إيتاي البارود",
          english: "Itai Baroud",
        },
        {
          id: "174",
          governorate_id: "6",
          arabic: "حوش عيسى",
          english: "Housh Eissa",
        },
        {
          id: "175",
          governorate_id: "6",
          arabic: "شبراخيت",
          english: "Shubrakhit",
        },
        {
          id: "176",
          governorate_id: "6",
          arabic: "كوم حمادة",
          english: "Kom Hamada",
        },
        {
          id: "177",
          governorate_id: "6",
          arabic: "بدر",
          english: "Badr",
        },
        {
          id: "178",
          governorate_id: "6",
          arabic: "وادي النطرون",
          english: "Wadi Natrun",
        },
        {
          id: "179",
          governorate_id: "6",
          arabic: "النوبارية الجديدة",
          english: "New Nubaria",
        },
        {
          id: "180",
          governorate_id: "6",
          arabic: "النوبارية",
          english: "Alnoubareya",
        },
        {
          id: "181",
          governorate_id: "7",
          arabic: "الفيوم",
          english: "Fayoum",
        },
        {
          id: "182",
          governorate_id: "7",
          arabic: "الفيوم الجديدة",
          english: "Fayoum El Gedida",
        },
        {
          id: "183",
          governorate_id: "7",
          arabic: "طامية",
          english: "Tamiya",
        },
        {
          id: "184",
          governorate_id: "7",
          arabic: "سنورس",
          english: "Snores",
        },
        {
          id: "185",
          governorate_id: "7",
          arabic: "إطسا",
          english: "Etsa",
        },
        {
          id: "186",
          governorate_id: "7",
          arabic: "إبشواي",
          english: "Epschway",
        },
        {
          id: "187",
          governorate_id: "7",
          arabic: "يوسف الصديق",
          english: "Yusuf El Sediaq",
        },
        {
          id: "188",
          governorate_id: "7",
          arabic: "الحادقة",
          english: "Hadqa",
        },
        {
          id: "189",
          governorate_id: "7",
          arabic: "اطسا",
          english: "Atsa",
        },
        {
          id: "190",
          governorate_id: "7",
          arabic: "الجامعة",
          english: "Algamaa",
        },
        {
          id: "191",
          governorate_id: "7",
          arabic: "السيالة",
          english: "Sayala",
        },
        {
          id: "192",
          governorate_id: "8",
          arabic: "طنطا",
          english: "Tanta",
        },
        {
          id: "193",
          governorate_id: "8",
          arabic: "المحلة الكبرى",
          english: "Al Mahalla Al Kobra",
        },
        {
          id: "194",
          governorate_id: "8",
          arabic: "كفر الزيات",
          english: "Kafr El Zayat",
        },
        {
          id: "195",
          governorate_id: "8",
          arabic: "زفتى",
          english: "Zefta",
        },
        {
          id: "196",
          governorate_id: "8",
          arabic: "السنطة",
          english: "El Santa",
        },
        {
          id: "197",
          governorate_id: "8",
          arabic: "قطور",
          english: "Qutour",
        },
        {
          id: "198",
          governorate_id: "8",
          arabic: "بسيون",
          english: "Basion",
        },
        {
          id: "199",
          governorate_id: "8",
          arabic: "سمنود",
          english: "Samannoud",
        },
        {
          id: "200",
          governorate_id: "9",
          arabic: "الإسماعيلية",
          english: "Ismailia",
        },
        {
          id: "201",
          governorate_id: "9",
          arabic: "فايد",
          english: "Fayed",
        },
        {
          id: "202",
          governorate_id: "9",
          arabic: "القنطرة شرق",
          english: "Qantara Sharq",
        },
        {
          id: "203",
          governorate_id: "9",
          arabic: "القنطرة غرب",
          english: "Qantara Gharb",
        },
        {
          id: "204",
          governorate_id: "9",
          arabic: "التل الكبير",
          english: "El Tal El Kabier",
        },
        {
          id: "205",
          governorate_id: "9",
          arabic: "أبو صوير",
          english: "Abu Sawir",
        },
        {
          id: "206",
          governorate_id: "9",
          arabic: "القصاصين الجديدة",
          english: "Kasasien El Gedida",
        },
        {
          id: "207",
          governorate_id: "9",
          arabic: "نفيشة",
          english: "Nefesha",
        },
        {
          id: "208",
          governorate_id: "9",
          arabic: "الشيخ زايد",
          english: "Sheikh Zayed",
        },
        {
          id: "209",
          governorate_id: "10",
          arabic: "شبين الكوم",
          english: "Shbeen El Koom",
        },
        {
          id: "210",
          governorate_id: "10",
          arabic: "مدينة السادات",
          english: "Sadat City",
        },
        {
          id: "211",
          governorate_id: "10",
          arabic: "منوف",
          english: "Menouf",
        },
        {
          id: "212",
          governorate_id: "10",
          arabic: "سرس الليان",
          english: "Sars El-Layan",
        },
        {
          id: "213",
          governorate_id: "10",
          arabic: "أشمون",
          english: "Ashmon",
        },
        {
          id: "214",
          governorate_id: "10",
          arabic: "الباجور",
          english: "Al Bagor",
        },
        {
          id: "215",
          governorate_id: "10",
          arabic: "قويسنا",
          english: "Quesna",
        },
        {
          id: "216",
          governorate_id: "10",
          arabic: "بركة السبع",
          english: "Berkat El Saba",
        },
        {
          id: "217",
          governorate_id: "10",
          arabic: "تلا",
          english: "Tala",
        },
        {
          id: "218",
          governorate_id: "10",
          arabic: "الشهداء",
          english: "Al Shohada",
        },
        {
          id: "219",
          governorate_id: "11",
          arabic: "المنيا",
          english: "Minya",
        },
        {
          id: "220",
          governorate_id: "11",
          arabic: "المنيا الجديدة",
          english: "Minya El Gedida",
        },
        {
          id: "221",
          governorate_id: "11",
          arabic: "العدوة",
          english: "El Adwa",
        },
        {
          id: "222",
          governorate_id: "11",
          arabic: "مغاغة",
          english: "Magagha",
        },
        {
          id: "223",
          governorate_id: "11",
          arabic: "بني مزار",
          english: "Bani Mazar",
        },
        {
          id: "224",
          governorate_id: "11",
          arabic: "مطاي",
          english: "Mattay",
        },
        {
          id: "225",
          governorate_id: "11",
          arabic: "سمالوط",
          english: "Samalut",
        },
        {
          id: "226",
          governorate_id: "11",
          arabic: "المدينة الفكرية",
          english: "Madinat El Fekria",
        },
        {
          id: "227",
          governorate_id: "11",
          arabic: "ملوي",
          english: "Meloy",
        },
        {
          id: "228",
          governorate_id: "11",
          arabic: "دير مواس",
          english: "Deir Mawas",
        },
        {
          id: "229",
          governorate_id: "11",
          arabic: "ابو قرقاص",
          english: "Abu Qurqas",
        },
        {
          id: "230",
          governorate_id: "11",
          arabic: "ارض سلطان",
          english: "Ard Sultan",
        },
        {
          id: "231",
          governorate_id: "12",
          arabic: "بنها",
          english: "Banha",
        },
        {
          id: "232",
          governorate_id: "12",
          arabic: "قليوب",
          english: "Qalyub",
        },
        {
          id: "233",
          governorate_id: "12",
          arabic: "شبرا الخيمة",
          english: "Shubra Al Khaimah",
        },
        {
          id: "234",
          governorate_id: "12",
          arabic: "القناطر الخيرية",
          english: "Al Qanater Charity",
        },
        {
          id: "235",
          governorate_id: "12",
          arabic: "الخانكة",
          english: "Khanka",
        },
        {
          id: "236",
          governorate_id: "12",
          arabic: "كفر شكر",
          english: "Kafr Shukr",
        },
        {
          id: "237",
          governorate_id: "12",
          arabic: "طوخ",
          english: "Tukh",
        },
        {
          id: "238",
          governorate_id: "12",
          arabic: "قها",
          english: "Qaha",
        },
        {
          id: "239",
          governorate_id: "12",
          arabic: "العبور",
          english: "Obour",
        },
        {
          id: "240",
          governorate_id: "12",
          arabic: "الخصوص",
          english: "Khosous",
        },
        {
          id: "241",
          governorate_id: "12",
          arabic: "شبين القناطر",
          english: "Shibin Al Qanater",
        },
        {
          id: "242",
          governorate_id: "12",
          arabic: "مسطرد",
          english: "Mostorod",
        },
        {
          id: "243",
          governorate_id: "13",
          arabic: "الخارجة",
          english: "El Kharga",
        },
        {
          id: "244",
          governorate_id: "13",
          arabic: "باريس",
          english: "Paris",
        },
        {
          id: "245",
          governorate_id: "13",
          arabic: "موط",
          english: "Mout",
        },
        {
          id: "246",
          governorate_id: "13",
          arabic: "الفرافرة",
          english: "Farafra",
        },
        {
          id: "247",
          governorate_id: "13",
          arabic: "بلاط",
          english: "Balat",
        },
        {
          id: "248",
          governorate_id: "13",
          arabic: "الداخلة",
          english: "Dakhla",
        },
        {
          id: "249",
          governorate_id: "14",
          arabic: "السويس",
          english: "Suez",
        },
        {
          id: "250",
          governorate_id: "14",
          arabic: "الجناين",
          english: "Alganayen",
        },
        {
          id: "251",
          governorate_id: "14",
          arabic: "عتاقة",
          english: "Ataqah",
        },
        {
          id: "252",
          governorate_id: "14",
          arabic: "العين السخنة",
          english: "Ain Sokhna",
        },
        {
          id: "253",
          governorate_id: "14",
          arabic: "فيصل",
          english: "Faysal",
        },
        {
          id: "254",
          governorate_id: "15",
          arabic: "أسوان",
          english: "Aswan",
        },
        {
          id: "255",
          governorate_id: "15",
          arabic: "أسوان الجديدة",
          english: "Aswan El Gedida",
        },
        {
          id: "256",
          governorate_id: "15",
          arabic: "دراو",
          english: "Drau",
        },
        {
          id: "257",
          governorate_id: "15",
          arabic: "كوم أمبو",
          english: "Kom Ombo",
        },
        {
          id: "258",
          governorate_id: "15",
          arabic: "نصر النوبة",
          english: "Nasr Al Nuba",
        },
        {
          id: "259",
          governorate_id: "15",
          arabic: "كلابشة",
          english: "Kalabsha",
        },
        {
          id: "260",
          governorate_id: "15",
          arabic: "إدفو",
          english: "Edfu",
        },
        {
          id: "261",
          governorate_id: "15",
          arabic: "الرديسية",
          english: "Al-Radisiyah",
        },
        {
          id: "262",
          governorate_id: "15",
          arabic: "البصيلية",
          english: "Al Basilia",
        },
        {
          id: "263",
          governorate_id: "15",
          arabic: "السباعية",
          english: "Al Sibaeia",
        },
        {
          id: "264",
          governorate_id: "15",
          arabic: "ابوسمبل السياحية",
          english: "Abo Simbl Al Siyahia",
        },
        {
          id: "265",
          governorate_id: "15",
          arabic: "مرسى علم",
          english: "Marsa Alam",
        },
        {
          id: "266",
          governorate_id: "16",
          arabic: "أسيوط",
          english: "Assiut",
        },
        {
          id: "267",
          governorate_id: "16",
          arabic: "أسيوط الجديدة",
          english: "Assiut El Gedida",
        },
        {
          id: "268",
          governorate_id: "16",
          arabic: "ديروط",
          english: "Dayrout",
        },
        {
          id: "269",
          governorate_id: "16",
          arabic: "منفلوط",
          english: "Manfalut",
        },
        {
          id: "270",
          governorate_id: "16",
          arabic: "القوصية",
          english: "Qusiya",
        },
        {
          id: "271",
          governorate_id: "16",
          arabic: "أبنوب",
          english: "Abnoub",
        },
        {
          id: "272",
          governorate_id: "16",
          arabic: "أبو تيج",
          english: "Abu Tig",
        },
        {
          id: "273",
          governorate_id: "16",
          arabic: "الغنايم",
          english: "El Ghanaim",
        },
        {
          id: "274",
          governorate_id: "16",
          arabic: "ساحل سليم",
          english: "Sahel Selim",
        },
        {
          id: "275",
          governorate_id: "16",
          arabic: "البداري",
          english: "El Badari",
        },
        {
          id: "276",
          governorate_id: "16",
          arabic: "صدفا",
          english: "Sidfa",
        },
        {
          id: "277",
          governorate_id: "17",
          arabic: "بني سويف",
          english: "Bani Sweif",
        },
        {
          id: "278",
          governorate_id: "17",
          arabic: "بني سويف الجديدة",
          english: "Beni Suef El Gedida",
        },
        {
          id: "279",
          governorate_id: "17",
          arabic: "الواسطى",
          english: "Al Wasta",
        },
        {
          id: "280",
          governorate_id: "17",
          arabic: "ناصر",
          english: "Naser",
        },
        {
          id: "281",
          governorate_id: "17",
          arabic: "إهناسيا",
          english: "Ehnasia",
        },
        {
          id: "282",
          governorate_id: "17",
          arabic: "ببا",
          english: "beba",
        },
        {
          id: "283",
          governorate_id: "17",
          arabic: "الفشن",
          english: "Fashn",
        },
        {
          id: "284",
          governorate_id: "17",
          arabic: "سمسطا",
          english: "Somasta",
        },
        {
          id: "285",
          governorate_id: "17",
          arabic: "الاباصيرى",
          english: "Alabbaseri",
        },
        {
          id: "286",
          governorate_id: "17",
          arabic: "مقبل",
          english: "Mokbel",
        },
        {
          id: "287",
          governorate_id: "18",
          arabic: "بورسعيد",
          english: "PorSaid",
        },
        {
          id: "288",
          governorate_id: "18",
          arabic: "بورفؤاد",
          english: "Port Fouad",
        },
        {
          id: "289",
          governorate_id: "18",
          arabic: "العرب",
          english: "Alarab",
        },
        {
          id: "290",
          governorate_id: "18",
          arabic: "حى الزهور",
          english: "Zohour",
        },
        {
          id: "291",
          governorate_id: "18",
          arabic: "حى الشرق",
          english: "Alsharq",
        },
        {
          id: "292",
          governorate_id: "18",
          arabic: "حى الضواحى",
          english: "Aldawahi",
        },
        {
          id: "293",
          governorate_id: "18",
          arabic: "حى المناخ",
          english: "Almanakh",
        },
        {
          id: "294",
          governorate_id: "18",
          arabic: "حى مبارك",
          english: "Mubarak",
        },
        {
          id: "295",
          governorate_id: "19",
          arabic: "دمياط",
          english: "Damietta",
        },
        {
          id: "296",
          governorate_id: "19",
          arabic: "دمياط الجديدة",
          english: "New Damietta",
        },
        {
          id: "297",
          governorate_id: "19",
          arabic: "رأس البر",
          english: "Ras El Bar",
        },
        {
          id: "298",
          governorate_id: "19",
          arabic: "فارسكور",
          english: "Faraskour",
        },
        {
          id: "299",
          governorate_id: "19",
          arabic: "الزرقا",
          english: "Zarqa",
        },
        {
          id: "300",
          governorate_id: "19",
          arabic: "السرو",
          english: "alsaru",
        },
        {
          id: "301",
          governorate_id: "19",
          arabic: "الروضة",
          english: "alruwda",
        },
        {
          id: "302",
          governorate_id: "19",
          arabic: "كفر البطيخ",
          english: "Kafr El-Batikh",
        },
        {
          id: "303",
          governorate_id: "19",
          arabic: "عزبة البرج",
          english: "Azbet Al Burg",
        },
        {
          id: "304",
          governorate_id: "19",
          arabic: "ميت أبو غالب",
          english: "Meet Abou Ghalib",
        },
        {
          id: "305",
          governorate_id: "19",
          arabic: "كفر سعد",
          english: "Kafr Saad",
        },
        {
          id: "306",
          governorate_id: "20",
          arabic: "الزقازيق",
          english: "Zagazig",
        },
        {
          id: "307",
          governorate_id: "20",
          arabic: "العاشر من رمضان",
          english: "Al Ashr Men Ramadan",
        },
        {
          id: "308",
          governorate_id: "20",
          arabic: "منيا القمح",
          english: "Minya Al Qamh",
        },
        {
          id: "309",
          governorate_id: "20",
          arabic: "بلبيس",
          english: "Belbeis",
        },
        {
          id: "310",
          governorate_id: "20",
          arabic: "مشتول السوق",
          english: "Mashtoul El Souq",
        },
        {
          id: "311",
          governorate_id: "20",
          arabic: "القنايات",
          english: "Qenaiat",
        },
        {
          id: "312",
          governorate_id: "20",
          arabic: "أبو حماد",
          english: "Abu Hammad",
        },
        {
          id: "313",
          governorate_id: "20",
          arabic: "القرين",
          english: "El Qurain",
        },
        {
          id: "314",
          governorate_id: "20",
          arabic: "ههيا",
          english: "Hehia",
        },
        {
          id: "315",
          governorate_id: "20",
          arabic: "أبو كبير",
          english: "Abu Kabir",
        },
        {
          id: "316",
          governorate_id: "20",
          arabic: "فاقوس",
          english: "Faccus",
        },
        {
          id: "317",
          governorate_id: "20",
          arabic: "الصالحية الجديدة",
          english: "El Salihia El Gedida",
        },
        {
          id: "318",
          governorate_id: "20",
          arabic: "الإبراهيمية",
          english: "Al Ibrahimiyah",
        },
        {
          id: "319",
          governorate_id: "20",
          arabic: "ديرب نجم",
          english: "Deirb Negm",
        },
        {
          id: "320",
          governorate_id: "20",
          arabic: "كفر صقر",
          english: "Kafr Saqr",
        },
        {
          id: "321",
          governorate_id: "20",
          arabic: "أولاد صقر",
          english: "Awlad Saqr",
        },
        {
          id: "322",
          governorate_id: "20",
          arabic: "الحسينية",
          english: "Husseiniya",
        },
        {
          id: "323",
          governorate_id: "20",
          arabic: "صان الحجر القبلية",
          english: "san alhajar alqablia",
        },
        {
          id: "324",
          governorate_id: "20",
          arabic: "منشأة أبو عمر",
          english: "Manshayat Abu Omar",
        },
        {
          id: "325",
          governorate_id: "21",
          arabic: "الطور",
          english: "Al Toor",
        },
        {
          id: "326",
          governorate_id: "21",
          arabic: "شرم الشيخ",
          english: "Sharm El-Shaikh",
        },
        {
          id: "327",
          governorate_id: "21",
          arabic: "دهب",
          english: "Dahab",
        },
        {
          id: "328",
          governorate_id: "21",
          arabic: "نويبع",
          english: "Nuweiba",
        },
        {
          id: "329",
          governorate_id: "21",
          arabic: "طابا",
          english: "Taba",
        },
        {
          id: "330",
          governorate_id: "21",
          arabic: "سانت كاترين",
          english: "Saint Catherine",
        },
        {
          id: "331",
          governorate_id: "21",
          arabic: "أبو رديس",
          english: "Abu Redis",
        },
        {
          id: "332",
          governorate_id: "21",
          arabic: "أبو زنيمة",
          english: "Abu Zenaima",
        },
        {
          id: "333",
          governorate_id: "21",
          arabic: "رأس سدر",
          english: "Ras Sidr",
        },
        {
          id: "334",
          governorate_id: "22",
          arabic: "كفر الشيخ",
          english: "Kafr El Sheikh",
        },
        {
          id: "335",
          governorate_id: "22",
          arabic: "وسط البلد كفر الشيخ",
          english: "Kafr El Sheikh Downtown",
        },
        {
          id: "336",
          governorate_id: "22",
          arabic: "دسوق",
          english: "Desouq",
        },
        {
          id: "337",
          governorate_id: "22",
          arabic: "فوه",
          english: "Fooh",
        },
        {
          id: "338",
          governorate_id: "22",
          arabic: "مطوبس",
          english: "Metobas",
        },
        {
          id: "339",
          governorate_id: "22",
          arabic: "برج البرلس",
          english: "Burg Al Burullus",
        },
        {
          id: "340",
          governorate_id: "22",
          arabic: "بلطيم",
          english: "Baltim",
        },
        {
          id: "341",
          governorate_id: "22",
          arabic: "مصيف بلطيم",
          english: "Masief Baltim",
        },
        {
          id: "342",
          governorate_id: "22",
          arabic: "الحامول",
          english: "Hamol",
        },
        {
          id: "343",
          governorate_id: "22",
          arabic: "بيلا",
          english: "Bella",
        },
        {
          id: "344",
          governorate_id: "22",
          arabic: "الرياض",
          english: "Riyadh",
        },
        {
          id: "345",
          governorate_id: "22",
          arabic: "سيدي سالم",
          english: "Sidi Salm",
        },
        {
          id: "346",
          governorate_id: "22",
          arabic: "قلين",
          english: "Qellen",
        },
        {
          id: "347",
          governorate_id: "22",
          arabic: "سيدي غازي",
          english: "Sidi Ghazi",
        },
        {
          id: "348",
          governorate_id: "23",
          arabic: "مرسى مطروح",
          english: "Marsa Matrouh",
        },
        {
          id: "349",
          governorate_id: "23",
          arabic: "الحمام",
          english: "El Hamam",
        },
        {
          id: "350",
          governorate_id: "23",
          arabic: "العلمين",
          english: "Alamein",
        },
        {
          id: "351",
          governorate_id: "23",
          arabic: "الضبعة",
          english: "Dabaa",
        },
        {
          id: "352",
          governorate_id: "23",
          arabic: "النجيلة",
          english: "Al-Nagila",
        },
        {
          id: "353",
          governorate_id: "23",
          arabic: "سيدي براني",
          english: "Sidi Brani",
        },
        {
          id: "354",
          governorate_id: "23",
          arabic: "السلوم",
          english: "Salloum",
        },
        {
          id: "355",
          governorate_id: "23",
          arabic: "سيوة",
          english: "Siwa",
        },
        {
          id: "356",
          governorate_id: "23",
          arabic: "مارينا",
          english: "Marina",
        },
        {
          id: "357",
          governorate_id: "23",
          arabic: "الساحل الشمالى",
          english: "North Coast",
        },
        {
          id: "358",
          governorate_id: "24",
          arabic: "الأقصر",
          english: "Luxor",
        },
        {
          id: "359",
          governorate_id: "24",
          arabic: "الأقصر الجديدة",
          english: "New Luxor",
        },
        {
          id: "360",
          governorate_id: "24",
          arabic: "إسنا",
          english: "Esna",
        },
        {
          id: "361",
          governorate_id: "24",
          arabic: "طيبة الجديدة",
          english: "New Tiba",
        },
        {
          id: "362",
          governorate_id: "24",
          arabic: "الزينية",
          english: "Al ziynia",
        },
        {
          id: "363",
          governorate_id: "24",
          arabic: "البياضية",
          english: "Al Bayadieh",
        },
        {
          id: "364",
          governorate_id: "24",
          arabic: "القرنة",
          english: "Al Qarna",
        },
        {
          id: "365",
          governorate_id: "24",
          arabic: "أرمنت",
          english: "Armant",
        },
        {
          id: "366",
          governorate_id: "24",
          arabic: "الطود",
          english: "Al Tud",
        },
        {
          id: "367",
          governorate_id: "25",
          arabic: "قنا",
          english: "Qena",
        },
        {
          id: "368",
          governorate_id: "25",
          arabic: "قنا الجديدة",
          english: "New Qena",
        },
        {
          id: "369",
          governorate_id: "25",
          arabic: "ابو طشت",
          english: "Abu Tesht",
        },
        {
          id: "370",
          governorate_id: "25",
          arabic: "نجع حمادي",
          english: "Nag Hammadi",
        },
        {
          id: "371",
          governorate_id: "25",
          arabic: "دشنا",
          english: "Deshna",
        },
        {
          id: "372",
          governorate_id: "25",
          arabic: "الوقف",
          english: "Alwaqf",
        },
        {
          id: "373",
          governorate_id: "25",
          arabic: "قفط",
          english: "Qaft",
        },
        {
          id: "374",
          governorate_id: "25",
          arabic: "نقادة",
          english: "Naqada",
        },
        {
          id: "375",
          governorate_id: "25",
          arabic: "فرشوط",
          english: "Farshout",
        },
        {
          id: "376",
          governorate_id: "25",
          arabic: "قوص",
          english: "Quos",
        },
        {
          id: "377",
          governorate_id: "26",
          arabic: "العريش",
          english: "Arish",
        },
        {
          id: "378",
          governorate_id: "26",
          arabic: "الشيخ زويد",
          english: "Sheikh Zowaid",
        },
        {
          id: "379",
          governorate_id: "26",
          arabic: "نخل",
          english: "Nakhl",
        },
        {
          id: "380",
          governorate_id: "26",
          arabic: "رفح",
          english: "Rafah",
        },
        {
          id: "381",
          governorate_id: "26",
          arabic: "بئر العبد",
          english: "Bir al-Abed",
        },
        {
          id: "382",
          governorate_id: "26",
          arabic: "الحسنة",
          english: "Al Hasana",
        },
        {
          id: "383",
          governorate_id: "27",
          arabic: "سوهاج",
          english: "Sohag",
        },
        {
          id: "384",
          governorate_id: "27",
          arabic: "سوهاج الجديدة",
          english: "Sohag El Gedida",
        },
        {
          id: "385",
          governorate_id: "27",
          arabic: "أخميم",
          english: "Akhmeem",
        },
        {
          id: "386",
          governorate_id: "27",
          arabic: "أخميم الجديدة",
          english: "Akhmim El Gedida",
        },
        {
          id: "387",
          governorate_id: "27",
          arabic: "البلينا",
          english: "Albalina",
        },
        {
          id: "388",
          governorate_id: "27",
          arabic: "المراغة",
          english: "El Maragha",
        },
        {
          id: "389",
          governorate_id: "27",
          arabic: "المنشأة",
          english: "almunsha'a",
        },
        {
          id: "390",
          governorate_id: "27",
          arabic: "دار السلام",
          english: "Dar AISalaam",
        },
        {
          id: "391",
          governorate_id: "27",
          arabic: "جرجا",
          english: "Gerga",
        },
        {
          id: "392",
          governorate_id: "27",
          arabic: "جهينة الغربية",
          english: "Jahina Al Gharbia",
        },
        {
          id: "393",
          governorate_id: "27",
          arabic: "ساقلته",
          english: "Saqilatuh",
        },
        {
          id: "394",
          governorate_id: "27",
          arabic: "طما",
          english: "Tama",
        },
        {
          id: "395",
          governorate_id: "27",
          arabic: "طهطا",
          english: "Tahta",
        },
        {
          id: "396",
          governorate_id: "27",
          arabic: "الكوثر",
          english: "Alkawthar",
        },
      ],
    };
  },
};
